sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t maximelebastard/alpine-uhttpd .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master



